//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attandce
    {
        public int aid { get; set; }
        public System.DateTime adate { get; set; }
        public int classid { get; set; }
        public int studentid { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual student student { get; set; }
    }
}
