//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.attandce = new HashSet<attandce>();
        }
    
        public int sid { get; set; }
        public string studentname { get; set; }
        public string studentsurname { get; set; }
        public System.DateTime studentbirth { get; set; }
        public string studentcity { get; set; }
        public string studenfather { get; set; }
        public string studentmother { get; set; }
        public byte[] studentphoto { get; set; }
        public int clid { get; set; }
    
        public virtual @class @class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attandce> attandce { get; set; }
    }
}
